### ISSUE TITLE
UEFI file not downloading

### ISSUE THREAD

**Issue by datboi0077** [WOA-Project/WOA-Deployer-Rpi#37]
When I use the deployer, It finds "install.wim" but gets an error when it tries to download the uefi.
Heres the Error log

2019-06-05 23:20:11.106 -07:00 [Verbose] The '"C:\W10IsoScripts"' exists
2019-06-05 23:21:18.428 -07:00 [Verbose] Default directory for WimFolder has been set to "G:\sources"
2019-06-05 23:21:18.430 -07:00 [Verbose] Trying to load WIM metadata file at '"G:\sources\install.wim"'
2019-06-05 23:21:18.444 -07:00 [Verbose] Getting WIM stream
2019-06-05 23:21:18.445 -07:00 [Verbose] (WIM) Finding Magic Bytes...
2019-06-05 23:21:18.445 -07:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-06-05 23:21:18.445 -07:00 [Verbose] (WIM) Finding WIM XML Data...
2019-06-05 23:21:18.445 -07:00 [Verbose] (WIM) Found WIM XML Data at 032223534762
2019-06-05 23:21:18.463 -07:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "3222353476", Images: [ImageMetadata { DirectoryCount: "19050", FileCount: "86689", TotalBytes: "14079140727", HardLinkBytes: "6227940913", CreationTime: Time { HighPart: "0x01D51953", LowPart: "0xDF4BAE60" }, LastModificationTime: Time { HighPart: "0x01D51C2F", LowPart: "0x1A13E1CF" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "Microsoft® Windows® Operating System", EditionId: "Professional", InstallationType: "Client", ServicingData: ServicingData { GdrDuRevision: "0", PKeyConfigVersion: "10.0.18912.1001;2016-01-01T00:00:00Z" }, ProductType: "WinNT", ProductSuite: "Terminal Server", Languages: Languages { Language: "en-US", Default: "en-US" }, Version: Version { Major: "10", Minor: "0", Build: "18912", SpBuild: "1001", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Pro", Description: "Windows 10 Pro", Flags: null, DiplayName: null, DisplayDescription: null, Index: "1" }] }
2019-06-05 23:21:18.465 -07:00 [Verbose] WIM metadata file at '"G:\sources\install.wim"' retrieved correctly
2019-06-05 23:21:44.389 -07:00 [Information] Downloading UEFI
2019-06-05 23:21:47.929 -07:00 [Error] An error has occurred
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'codeload.github.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishGetStreamAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.GitHubMixin.<OpenBranchStream>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Raspberry.Tasks.DownloadUefi.<Execute>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Execution.ScriptRunner.<Run>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Execution.ScriptRunner.<Run>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Raspberry.WoaDeployer.<Deploy>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Raspberry.Gui.ViewModels.DeploymentViewModel.<Deploy>d__20.MoveNext() in D:\a\1\s\Source\Deployer.Raspberry.Gui\ViewModels\DeploymentViewModel.cs:line 82
2019-06-05 23:21:47.938 -07:00 [Information] Error: An error occurred while sending the request.
2019-06-05 23:32:50.293 -07:00 [Information] Downloading UEFI

**Comment by dbzdivik** [comment]
+1
[Log-20190727.txt](https://github.com/WOA-Project/WOA-Deployer-Rpi/files/3438336/Log-20190727.txt)
