### ISSUE TITLE
 Error: Sequence contains no elements

### ISSUE THREAD

**Issue by tajummal-lab** [WOA-Project/WOA-Deployer-Rpi#52]
2019-11-02 07:42:11.617 -07:00 [Verbose] The '""' does not exist
2019-11-02 07:43:02.776 -07:00 [Verbose] Default directory for WimFolder has been set to "I:\"
2019-11-02 07:43:02.781 -07:00 [Verbose] Trying to load WIM metadata file at '"I:\bootmgr.efi"'
2019-11-02 07:43:03.070 -07:00 [Verbose] Getting WIM stream
2019-11-02 07:43:03.071 -07:00 [Verbose] (WIM) Finding Magic Bytes...
2019-11-02 07:43:03.436 -07:00 [Verbose] (WIM) Found Magic Bytes at 354448
2019-11-02 07:43:03.436 -07:00 [Verbose] (WIM) Finding WIM XML Data...
2019-11-02 07:43:03.437 -07:00 [Verbose] (WIM) Found WIM XML Data at 35444812250129460950637022
2019-11-02 07:43:03.452 -07:00 [Error] WIM file error
Deployer.Exceptions.InvalidWimFileException: Could not read the metadata from the WIM file. Please, check it's a valid .WIM file ---> System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderWimMetadata.Read9_WIM()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at Deployer.Services.Wim.WindowsImageMetadataReaderBase.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Deployer.Services.Wim.WindowsImageMetadataReaderBase.Load(Stream stream)
   at Deployer.Raspberry.Gui.ViewModels.WimPickViewModel.LoadWimMetadata(String path) in D:\a\1\s\Source\Deployer.Raspberry.Gui\ViewModels\WimPickViewModel.cs:line 87
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
2019-11-02 07:49:01.167 -07:00 [Verbose] The '"I:\"' exists
2019-11-02 07:49:06.579 -07:00 [Verbose] Default directory for WimFolder has been set to "I:\sources"
2019-11-02 07:49:06.586 -07:00 [Verbose] Trying to load WIM metadata file at '"I:\sources\install.wim"'
2019-11-02 07:49:06.941 -07:00 [Verbose] Getting WIM stream
2019-11-02 07:49:06.943 -07:00 [Verbose] (WIM) Finding Magic Bytes...
2019-11-02 07:49:06.975 -07:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-11-02 07:49:06.975 -07:00 [Verbose] (WIM) Finding WIM XML Data...
2019-11-02 07:49:06.975 -07:00 [Verbose] (WIM) Found WIM XML Data at 045645759392
2019-11-02 07:49:07.065 -07:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "4564575939", Images: [ImageMetadata { DirectoryCount: "24968", FileCount: "120040", TotalBytes: "19396788036", HardLinkBytes: "8016310930", CreationTime: Time { HighPart: "0x01D3D214", LowPart: "0xE5C57629" }, LastModificationTime: Time { HighPart: "0x01D59188", LowPart: "0x3F365D4A" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "MicrosoftÂ® WindowsÂ® Operating System", EditionId: "Professional", InstallationType: "Client", ServicingData: ServicingData { GdrDuRevision: "0", PKeyConfigVersion: "10.0.17134.982;2016-01-01T00:00:00Z" }, ProductType: "WinNT", ProductSuite: "Terminal Server", Languages: Languages { Language: "en-US", Default: "en-US" }, Version: Version { Major: "10", Minor: "0", Build: "17134", SpBuild: "984", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Pro", Description: "Windows 10 Pro", Flags: null, DiplayName: "Windows 10 Pro", DisplayDescription: "Windows 10 Pro", Index: "1" }] }
2019-11-02 07:49:07.073 -07:00 [Verbose] WIM metadata file at '"I:\sources\install.wim"' retrieved correctly
2019-11-02 07:49:31.589 -07:00 [Information] Downloading UEFI
2019-11-02 07:57:39.342 -07:00 [Information] Fetching zip from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan95xx-windows/lan9500-wdf-v18.12.18.0.zip
2019-11-02 07:58:11.223 -07:00 [Information] Fetching zip from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan78xx-windows/lan7800-wdf-v18.12.14.0.zip
2019-11-02 07:58:23.804 -07:00 [Information] Fetching zip from https://pi64.win/wp-content/uploads/2019/02/usb-drivers.zip
2019-11-02 07:58:27.699 -07:00 [Information] Fetching from GitHub subfolder: https://github.com/driver1998/bsp/bsp-master/prebuilt to Downloaded\Drivers\BSP Drivers
2019-11-02 07:58:35.128 -07:00 [Information] License from Downloaded\Drivers\USB\license.md
2019-11-02 08:11:52.356 -07:00 [Information] Deploying Windows
2019-11-02 08:11:52.362 -07:00 [Information] Flashing GPT image...
2019-11-02 08:11:52.372 -07:00 [Verbose] We are about to run Etcher: "Core\Tools\Etcher-Cli\x86\Etcher" "-d \\.\PHYSICALDRIVE1 \"Core\gpt.zip\" --yes --no-unmount"
2019-11-02 08:11:52.376 -07:00 [Verbose] Starting process { FileName: "Core\Tools\Etcher-Cli\x86\Etcher", Arguments: "-d \\.\PHYSICALDRIVE1 \"Core\gpt.zip\" --yes --no-unmount" }
2019-11-02 08:11:52.694 -07:00 [Verbose] Process started sucessfully
2019-11-02 08:13:04.824 -07:00 [Information] Validating flashed image...
2019-11-02 08:13:40.059 -07:00 [Information] GPT image flashed
2019-11-02 08:13:40.063 -07:00 [Verbose] Creating Windows partition...
2019-11-02 08:13:40.451 -07:00 [Error] An error has occurred
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Deployer.NetFx.LowLevelApi.<CreatePartition>d__14.MoveNext() in D:\a\1\s\Source\DeployerPlatform\Deployer.NetFx\LowLevelApi.cs:line 240
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Raspberry.RaspberryDisklayoutPreparer.<CreateWindowsPartition>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Raspberry.RaspberryDisklayoutPreparer.<Prepare>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Tasks.DeployWindows.<Execute>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Execution.ScriptRunner.<Run>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Deployer.Execution.ScriptRunner.<Run>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Raspberry.WoaDeployer.<Deploy>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Raspberry.Gui.ViewModels.DeploymentViewModel.<Deploy>d__20.MoveNext() in D:\a\1\s\Source\Deployer.Raspberry.Gui\ViewModels\DeploymentViewModel.cs:line 82
2019-11-02 08:13:40.466 -07:00 [Information] Error: Sequence contains no elements
2019-11-02 08:18:23.300 -07:00 [Verbose] The '"I:\sources"' exists
2019-11-02 08:18:27.515 -07:00 [Verbose] Default directory for WimFolder has been set to "I:\sources"
2019-11-02 08:18:27.519 -07:00 [Verbose] Trying to load WIM metadata file at '"I:\sources\install.wim"'
2019-11-02 08:18:27.829 -07:00 [Verbose] Getting WIM stream
2019-11-02 08:18:27.831 -07:00 [Verbose] (WIM) Finding Magic Bytes...
2019-11-02 08:18:27.836 -07:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-11-02 08:18:27.836 -07:00 [Verbose] (WIM) Finding WIM XML Data...
2019-11-02 08:18:27.836 -07:00 [Verbose] (WIM) Found WIM XML Data at 045645759392
2019-11-02 08:18:27.878 -07:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "4564575939", Images: [ImageMetadata { DirectoryCount: "24968", FileCount: "120040", TotalBytes: "19396788036", HardLinkBytes: "8016310930", CreationTime: Time { HighPart: "0x01D3D214", LowPart: "0xE5C57629" }, LastModificationTime: Time { HighPart: "0x01D59188", LowPart: "0x3F365D4A" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "MicrosoftÂ® WindowsÂ® Operating System", EditionId: "Professional", InstallationType: "Client", ServicingData: ServicingData { GdrDuRevision: "0", PKeyConfigVersion: "10.0.17134.982;2016-01-01T00:00:00Z" }, ProductType: "WinNT", ProductSuite: "Terminal Server", Languages: Languages { Language: "en-US", Default: "en-US" }, Version: Version { Major: "10", Minor: "0", Build: "17134", SpBuild: "984", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Pro", Description: "Windows 10 Pro", Flags: null, DiplayName: "Windows 10 Pro", DisplayDescription: "Windows 10 Pro", Index: "1" }] }
2019-11-02 08:18:27.883 -07:00 [Verbose] WIM metadata file at '"I:\sources\install.wim"' retrieved correctly
2019-11-02 08:18:36.461 -07:00 [Information] Downloading UEFI
2019-11-02 08:18:36.468 -07:00 [Warning] UEFI was already downloaded. Skipping download.
2019-11-02 08:18:36.477 -07:00 [Information] Fetching zip from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan95xx-windows/lan9500-wdf-v18.12.18.0.zip
2019-11-02 08:18:36.487 -07:00 [Information] Fetching zip from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan78xx-windows/lan7800-wdf-v18.12.14.0.zip
2019-11-02 08:18:36.494 -07:00 [Information] Fetching zip from https://pi64.win/wp-content/uploads/2019/02/usb-drivers.zip
2019-11-02 08:18:36.512 -07:00 [Information] Fetching from GitHub subfolder: https://github.com/driver1998/bsp/bsp-master/prebuilt to Downloaded\Drivers\BSP Drivers
2019-11-02 08:18:36.515 -07:00 [Warning] "https://github.com/driver1998/bsp""bsp-master/prebuilt" was already downloaded. Skipping download.
2019-11-02 08:18:36.530 -07:00 [Information] License from Downloaded\Drivers\USB\license.md
2019-11-02 08:18:39.677 -07:00 [Information] Deploying Windows
2019-11-02 08:18:39.685 -07:00 [Information] Flashing GPT image...
2019-11-02 08:18:39.694 -07:00 [Verbose] We are about to run Etcher: "Core\Tools\Etcher-Cli\x86\Etcher" "-d \\.\PHYSICALDRIVE1 \"Core\gpt.zip\" --yes --no-unmount"
2019-11-02 08:18:39.701 -07:00 [Verbose] Starting process { FileName: "Core\Tools\Etcher-Cli\x86\Etcher", Arguments: "-d \\.\PHYSICALDRIVE1 \"Core\gpt.zip\" --yes --no-unmount" }
2019-11-02 08:18:39.719 -07:00 [Verbose] Process started sucessfully
2019-11-02 08:19:27.077 -07:00 [Verbose] The '"I:\sources"' exists
2019-11-02 08:19:29.877 -07:00 [Verbose] Default directory for WimFolder has been set to "I:\sources"
2019-11-02 08:19:29.884 -07:00 [Verbose] Trying to load WIM metadata file at '"I:\sources\install.wim"'
2019-11-02 08:19:30.280 -07:00 [Verbose] Getting WIM stream
2019-11-02 08:19:30.282 -07:00 [Verbose] (WIM) Finding Magic Bytes...
2019-11-02 08:19:30.289 -07:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-11-02 08:19:30.289 -07:00 [Verbose] (WIM) Finding WIM XML Data...
2019-11-02 08:19:30.289 -07:00 [Verbose] (WIM) Found WIM XML Data at 045645759392
2019-11-02 08:19:30.337 -07:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "4564575939", Images: [ImageMetadata { DirectoryCount: "24968", FileCount: "120040", TotalBytes: "19396788036", HardLinkBytes: "8016310930", CreationTime: Time { HighPart: "0x01D3D214", LowPart: "0xE5C57629" }, LastModificationTime: Time { HighPart: "0x01D59188", LowPart: "0x3F365D4A" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "MicrosoftÂ® WindowsÂ® Operating System", EditionId: "Professional", InstallationType: "Client", ServicingData: ServicingData { GdrDuRevision: "0", PKeyConfigVersion: "10.0.17134.982;2016-01-01T00:00:00Z" }, ProductType: "WinNT", ProductSuite: "Terminal Server", Languages: Languages { Language: "en-US", Default: "en-US" }, Version: Version { Major: "10", Minor: "0", Build: "17134", SpBuild: "984", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Pro", Description: "Windows 10 Pro", Flags: null, DiplayName: "Windows 10 Pro", DisplayDescription: "Windows 10 Pro", Index: "1" }] }
2019-11-02 08:19:30.343 -07:00 [Verbose] WIM metadata file at '"I:\sources\install.wim"' retrieved correctly
2019-11-02 08:19:41.294 -07:00 [Information] Downloading UEFI
2019-11-02 08:19:41.304 -07:00 [Warning] UEFI was already downloaded. Skipping download.
2019-11-02 08:19:41.312 -07:00 [Information] Fetching zip from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan95xx-windows/lan9500-wdf-v18.12.18.0.zip
2019-11-02 08:19:41.331 -07:00 [Information] Fetching zip from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan78xx-windows/lan7800-wdf-v18.12.14.0.zip
2019-11-02 08:19:41.348 -07:00 [Information] Fetching zip from https://pi64.win/wp-content/uploads/2019/02/usb-drivers.zip
2019-11-02 08:19:41.364 -07:00 [Information] Fetching from GitHub subfolder: https://github.com/driver1998/bsp/bsp-master/prebuilt to Downloaded\Drivers\BSP Drivers
2019-11-02 08:19:41.366 -07:00 [Warning] "https://github.com/driver1998/bsp""bsp-master/prebuilt" was already downloaded. Skipping download.
2019-11-02 08:19:41.388 -07:00 [Information] License from Downloaded\Drivers\USB\license.md
2019-11-02 08:19:47.614 -07:00 [Information] Deploying Windows
2019-11-02 08:19:47.619 -07:00 [Information] Flashing GPT image...
2019-11-02 08:19:47.627 -07:00 [Verbose] We are about to run Etcher: "Core\Tools\Etcher-Cli\x86\Etcher" "-d \\.\PHYSICALDRIVE1 \"Core\gpt.zip\" --yes --no-unmount"
2019-11-02 08:19:47.634 -07:00 [Verbose] Starting process { FileName: "Core\Tools\Etcher-Cli\x86\Etcher", Arguments: "-d \\.\PHYSICALDRIVE1 \"Core\gpt.zip\" --yes --no-unmount" }
2019-11-02 08:19:47.653 -07:00 [Verbose] Process started sucessfully
2019-11-02 08:22:33.443 -07:00 [Verbose] The '"I:\sources"' exists
2019-11-02 08:22:36.897 -07:00 [Verbose] Default directory for WimFolder has been set to "I:\sources"
2019-11-02 08:22:36.901 -07:00 [Verbose] Trying to load WIM metadata file at '"I:\sources\install.wim"'
2019-11-02 08:22:37.225 -07:00 [Verbose] Getting WIM stream
2019-11-02 08:22:37.226 -07:00 [Verbose] (WIM) Finding Magic Bytes...
2019-11-02 08:22:37.231 -07:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-11-02 08:22:37.231 -07:00 [Verbose] (WIM) Finding WIM XML Data...
2019-11-02 08:22:37.232 -07:00 [Verbose] (WIM) Found WIM XML Data at 045645759392
2019-11-02 08:22:37.280 -07:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "4564575939", Images: [ImageMetadata { DirectoryCount: "24968", FileCount: "120040", TotalBytes: "19396788036", HardLinkBytes: "8016310930", CreationTime: Time { HighPart: "0x01D3D214", LowPart: "0xE5C57629" }, LastModificationTime: Time { HighPart: "0x01D59188", LowPart: "0x3F365D4A" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "MicrosoftÂ® WindowsÂ® Operating System", EditionId: "Professional", InstallationType: "Client", ServicingData: ServicingData { GdrDuRevision: "0", PKeyConfigVersion: "10.0.17134.982;2016-01-01T00:00:00Z" }, ProductType: "WinNT", ProductSuite: "Terminal Server", Languages: Languages { Language: "en-US", Default: "en-US" }, Version: Version { Major: "10", Minor: "0", Build: "17134", SpBuild: "984", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Pro", Description: "Windows 10 Pro", Flags: null, DiplayName: "Windows 10 Pro", DisplayDescription: "Windows 10 Pro", Index: "1" }] }
2019-11-02 08:22:37.285 -07:00 [Verbose] WIM metadata file at '"I:\sources\install.wim"' retrieved correctly
2019-11-02 08:22:43.546 -07:00 [Information] Downloading UEFI
2019-11-02 08:22:43.553 -07:00 [Warning] UEFI was already downloaded. Skipping download.
2019-11-02 08:22:43.564 -07:00 [Information] Fetching zip from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan95xx-windows/lan9500-wdf-v18.12.18.0.zip
2019-11-02 08:22:43.575 -07:00 [Information] Fetching zip from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan78xx-windows/lan7800-wdf-v18.12.14.0.zip
2019-11-02 08:22:43.581 -07:00 [Information] Fetching zip from https://pi64.win/wp-content/uploads/2019/02/usb-drivers.zip
2019-11-02 08:22:43.588 -07:00 [Information] Fetching from GitHub subfolder: https://github.com/driver1998/bsp/bsp-master/prebuilt to Downloaded\Drivers\BSP Drivers
2019-11-02 08:22:43.590 -07:00 [Warning] "https://github.com/driver1998/bsp""bsp-master/prebuilt" was already downloaded. Skipping download.
2019-11-02 08:22:43.598 -07:00 [Information] License from Downloaded\Drivers\USB\license.md
2019-11-02 08:22:46.020 -07:00 [Information] Deploying Windows
2019-11-02 08:22:46.026 -07:00 [Information] Flashing GPT image...
2019-11-02 08:22:46.035 -07:00 [Verbose] We are about to run Etcher: "Core\Tools\Etcher-Cli\x86\Etcher" "-d \\.\PHYSICALDRIVE2 \"Core\gpt.zip\" --yes --no-unmount"
2019-11-02 08:22:46.040 -07:00 [Verbose] Starting process { FileName: "Core\Tools\Etcher-Cli\x86\Etcher", Arguments: "-d \\.\PHYSICALDRIVE2 \"Core\gpt.zip\" --yes --no-unmount" }
2019-11-02 08:22:46.059 -07:00 [Verbose] Process started sucessfully
2019-11-02 08:36:08.163 -07:00 [Verbose] The '"I:\sources"' exists
2019-11-02 08:36:12.469 -07:00 [Verbose] Default directory for WimFolder has been set to "I:\sources"
2019-11-02 08:36:12.473 -07:00 [Verbose] Trying to load WIM metadata file at '"I:\sources\install.wim"'
2019-11-02 08:36:12.795 -07:00 [Verbose] Getting WIM stream
2019-11-02 08:36:12.797 -07:00 [Verbose] (WIM) Finding Magic Bytes...
2019-11-02 08:36:12.802 -07:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-11-02 08:36:12.802 -07:00 [Verbose] (WIM) Finding WIM XML Data...
2019-11-02 08:36:12.802 -07:00 [Verbose] (WIM) Found WIM XML Data at 045645759392
2019-11-02 08:36:12.851 -07:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "4564575939", Images: [ImageMetadata { DirectoryCount: "24968", FileCount: "120040", TotalBytes: "19396788036", HardLinkBytes: "8016310930", CreationTime: Time { HighPart: "0x01D3D214", LowPart: "0xE5C57629" }, LastModificationTime: Time { HighPart: "0x01D59188", LowPart: "0x3F365D4A" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "MicrosoftÂ® WindowsÂ® Operating System", EditionId: "Professional", InstallationType: "Client", ServicingData: ServicingData { GdrDuRevision: "0", PKeyConfigVersion: "10.0.17134.982;2016-01-01T00:00:00Z" }, ProductType: "WinNT", ProductSuite: "Terminal Server", Languages: Languages { Language: "en-US", Default: "en-US" }, Version: Version { Major: "10", Minor: "0", Build: "17134", SpBuild: "984", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Pro", Description: "Windows 10 Pro", Flags: null, DiplayName: "Windows 10 Pro", DisplayDescription: "Windows 10 Pro", Index: "1" }] }
2019-11-02 08:36:12.856 -07:00 [Verbose] WIM metadata file at '"I:\sources\install.wim"' retrieved correctly
2019-11-02 08:36:17.169 -07:00 [Information] Downloading UEFI
2019-11-02 08:36:17.176 -07:00 [Warning] UEFI was already downloaded. Skipping download.
2019-11-02 08:36:17.190 -07:00 [Information] Fetching zip from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan95xx-windows/lan9500-wdf-v18.12.18.0.zip
2019-11-02 08:36:17.215 -07:00 [Information] Fetching zip from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan78xx-windows/lan7800-wdf-v18.12.14.0.zip
2019-11-02 08:36:17.233 -07:00 [Information] Fetching zip from https://pi64.win/wp-content/uploads/2019/02/usb-drivers.zip
2019-11-02 08:36:17.251 -07:00 [Information] Fetching from GitHub subfolder: https://github.com/driver1998/bsp/bsp-master/prebuilt to Downloaded\Drivers\BSP Drivers
2019-11-02 08:36:17.254 -07:00 [Warning] "https://github.com/driver1998/bsp""bsp-master/prebuilt" was already downloaded. Skipping download.
2019-11-02 08:36:17.268 -07:00 [Information] License from Downloaded\Drivers\USB\license.md
2019-11-02 08:36:19.793 -07:00 [Information] Deploying Windows
2019-11-02 08:36:19.802 -07:00 [Information] Flashing GPT image...
2019-11-02 08:36:19.812 -07:00 [Verbose] We are about to run Etcher: "Core\Tools\Etcher-Cli\x86\Etcher" "-d \\.\PHYSICALDRIVE1 \"Core\gpt.zip\" --yes --no-unmount"
2019-11-02 08:36:19.818 -07:00 [Verbose] Starting process { FileName: "Core\Tools\Etcher-Cli\x86\Etcher", Arguments: "-d \\.\PHYSICALDRIVE1 \"Core\gpt.zip\" --yes --no-unmount" }
2019-11-02 08:36:19.836 -07:00 [Verbose] Process started sucessfully
2019-11-02 08:37:09.719 -07:00 [Information] Validating flashed image...
2019-11-02 08:37:44.194 -07:00 [Information] GPT image flashed
2019-11-02 08:37:44.199 -07:00 [Verbose] Creating Windows partition...
2019-11-02 08:37:44.405 -07:00 [Error] An error has occurred
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Deployer.NetFx.LowLevelApi.<CreatePartition>d__14.MoveNext() in D:\a\1\s\Source\DeployerPlatform\Deployer.NetFx\LowLevelApi.cs:line 240
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Raspberry.RaspberryDisklayoutPreparer.<CreateWindowsPartition>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Raspberry.RaspberryDisklayoutPreparer.<Prepare>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Tasks.DeployWindows.<Execute>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Execution.ScriptRunner.<Run>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Deployer.Execution.ScriptRunner.<Run>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Raspberry.WoaDeployer.<Deploy>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Raspberry.Gui.ViewModels.DeploymentViewModel.<Deploy>d__20.MoveNext() in D:\a\1\s\Source\Deployer.Raspberry.Gui\ViewModels\DeploymentViewModel.cs:line 82
2019-11-02 08:37:44.420 -07:00 [Information] Error: Sequence contains no elements

**Comment by SuperJMN** [comment]
The problem is related to the .wim file you provided. Please, download another .wim (another build9 file and try again.
