### ISSUE TITLE
Formatting out of sequence, possibly need to be serialized steps?

### ISSUE THREAD

**Issue by N129BZ** [WOA-Project/WOA-Deployer-Rpi#8]
I walked away from my laptop for a few minutes while the deployment was running.  When I came back, there were two format disk dialogs, one for the boot partition and a second for the windows os.  I evidently ran them out of sequence (both actually formatted just fine) but then the following deployment failed.  The deployment succeeded on the second try.  Apparently something waiting for the formatting steps to complete failed on the first attempt.  Log text:

2019-02-20 12:16:46.534 -05:00 [Verbose] The '""' does not exist
2019-02-20 13:05:22.272 -05:00 [Verbose] The '""' does not exist
2019-02-20 13:06:22.294 -05:00 [Verbose] Default directory for WimFolder has been set to "F:\sources"
2019-02-20 13:06:22.298 -05:00 [Verbose] Trying to load WIM metadata file at '"F:\sources\install.wim"'
2019-02-20 13:06:22.481 -05:00 [Verbose] Getting WIM stream
2019-02-20 13:06:22.484 -05:00 [Verbose] (WIM) Finding Magic Bytes...
2019-02-20 13:06:22.485 -05:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-02-20 13:06:22.485 -05:00 [Verbose] (WIM) Finding WIM XML Data...
2019-02-20 13:06:22.487 -05:00 [Verbose] (WIM) Found WIM XML Data at 043418977782
2019-02-20 13:06:22.518 -05:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "4341897778", Images: [ImageMetadata { DirectoryCount: "22565", FileCount: "98622", TotalBytes: "17049204181", HardLinkBytes: "6590715483", CreationTime: Time { HighPart: "0x01D44CED", LowPart: "0x43022989" }, LastModificationTime: Time { HighPart: "0x01D4C944", LowPart: "0x0061F20D" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "Microsoft® Windows® Operating System", EditionId: "Professional", InstallationType: "Client", ServicingData: ServicingData { GdrDuRevision: "0", PKeyConfigVersion: "10.0.17763.1;2016-01-01T00:00:00Z" }, ProductType: "WinNT", ProductSuite: "Terminal Server", Languages: Languages { Language: "en-US", Default: "en-US" }, Version: Version { Major: "10", Minor: "0", Build: "17763", SpBuild: "292", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Pro", Description: "Windows 10 Pro", Flags: null, DiplayName: "Windows 10 Pro", DisplayDescription: "Windows 10 Pro", Index: "1" }] }
2019-02-20 13:06:22.522 -05:00 [Verbose] WIM metadata file at '"F:\sources\install.wim"' retrieved correctly
2019-02-20 13:06:46.382 -05:00 [Information] Downloading UEFI
2019-02-20 13:07:19.877 -05:00 [Information] Zip Unpack from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan95xx-windows/lan9500-wdf-v18.12.18.0.zip to Downloaded\Drivers\LAN95XX
2019-02-20 13:07:27.236 -05:00 [Verbose] Copying directory "C:\Users\n129b\AppData\Local\Temp\3fkazoms.dpl" to "Downloaded\Drivers\LAN95XX"
2019-02-20 13:07:28.886 -05:00 [Information] Zip Unpack from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan78xx-windows/lan7800-wdf-v18.12.14.0.zip to Downloaded\Drivers\LAN78XX
2019-02-20 13:07:34.591 -05:00 [Verbose] Copying directory "C:\Users\n129b\AppData\Local\Temp\tiytjdv5.reg" to "Downloaded\Drivers\LAN78XX"
2019-02-20 13:07:38.150 -05:00 [Information] Zip Unpack from https://pi64.win/wp-content/uploads/2019/02/usb-drivers.zip to Downloaded\Drivers\USB
2019-02-20 13:07:39.329 -05:00 [Verbose] Copying directory "C:\Users\n129b\AppData\Local\Temp\cin0pz2h.gon" to "Downloaded\Drivers\USB"
2019-02-20 13:07:39.458 -05:00 [Information] Fetching from GitHub subfolder: https://github.com/driver1998/bsp/bsp-master/prebuilt to Downloaded\Drivers\BSP Drivers
2019-02-20 13:07:41.040 -05:00 [Information] License from Downloaded\Drivers\USB\license.md
2019-02-20 13:07:46.387 -05:00 [Information] Deploying Windows
2019-02-20 13:07:46.392 -05:00 [Information] Flashing GPT image...
2019-02-20 13:07:46.397 -05:00 [Verbose] We are about to run Etcher: "Core\Tools\Etcher-Cli\x86\Etcher" "-d \\.\PHYSICALDRIVE1 \"Core\gpt.zip\" --yes --no-unmount"
2019-02-20 13:07:46.464 -05:00 [Verbose] Starting process { FileName: "Core\Tools\Etcher-Cli\x86\Etcher", Arguments: "-d \\.\PHYSICALDRIVE1 \"Core\gpt.zip\" --yes --no-unmount" }
2019-02-20 13:07:55.264 -05:00 [Verbose] Process started sucessfully
2019-02-20 13:09:21.732 -05:00 [Information] Validating flashed image...
2019-02-20 13:10:16.658 -05:00 [Information] GPT image flashed
2019-02-20 13:10:16.661 -05:00 [Verbose] Creating Windows partition...
2019-02-20 13:10:18.722 -05:00 [Verbose] Mounting volume "Label: , Size: 0 b, Partition: Disk: Number: 1, Size: 29.72 GB, AllocatedSize: 29.72 GB, Number: 3, Letter: "
2019-02-20 13:10:30.222 -05:00 [Verbose] Windows Partition created successfully
2019-02-20 13:10:30.224 -05:00 [Information] Preparing for Windows deployment
2019-02-20 13:10:30.228 -05:00 [Verbose] Getting "WindowsARM" volume
2019-02-20 13:10:30.867 -05:00 [Information] Deploying Windows...
2019-02-20 13:10:30.871 -05:00 [Verbose] Checking image at "F:\sources\install.wim", with index "F:\sources\install.wim"
2019-02-20 13:10:30.872 -05:00 [Verbose] Image file at '"F:\sources\install.wim"' exists
2019-02-20 13:10:30.872 -05:00 [Verbose] Getting WIM stream
2019-02-20 13:10:30.872 -05:00 [Verbose] (WIM) Finding Magic Bytes...
2019-02-20 13:10:30.872 -05:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-02-20 13:10:30.872 -05:00 [Verbose] (WIM) Finding WIM XML Data...
2019-02-20 13:10:30.872 -05:00 [Verbose] (WIM) Found WIM XML Data at 043418977782
2019-02-20 13:10:30.881 -05:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "4341897778", Images: [ImageMetadata { DirectoryCount: "22565", FileCount: "98622", TotalBytes: "17049204181", HardLinkBytes: "6590715483", CreationTime: Time { HighPart: "0x01D44CED", LowPart: "0x43022989" }, LastModificationTime: Time { HighPart: "0x01D4C944", LowPart: "0x0061F20D" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "Microsoft® Windows® Operating System", EditionId: "Professional", InstallationType: "Client", ServicingData: ServicingData { GdrDuRevision: "0", PKeyConfigVersion: "10.0.17763.1;2016-01-01T00:00:00Z" }, ProductType: "WinNT", ProductSuite: "Terminal Server", Languages: Languages { Language: "en-US", Default: "en-US" }, Version: Version { Major: "10", Minor: "0", Build: "17763", SpBuild: "292", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Pro", Description: "Windows 10 Pro", Flags: null, DiplayName: "Windows 10 Pro", DisplayDescription: "Windows 10 Pro", Index: "1" }] }
2019-02-20 13:10:30.881 -05:00 [Verbose] We are about to run DISM: "C:\WINDOWS\SysNative\dism.exe" "/Apply-Image  /ImageFile:\"F:\sources\install.wim\" /Index:1 /ApplyDir:H:\"
2019-02-20 13:10:30.881 -05:00 [Verbose] Starting process { FileName: "C:\WINDOWS\SysNative\dism.exe", Arguments: "/Apply-Image  /ImageFile:\"F:\sources\install.wim\" /Index:1 /ApplyDir:H:\" }
2019-02-20 13:10:30.913 -05:00 [Verbose] Process started sucessfully
2019-02-20 13:12:25.943 -05:00 [Error] An error has occurred
Deployer.Exceptions.DeploymentException: There has been a problem during deployment: DISM exited with code 5.
   at Deployer.Filesystem.FullFx.DismImageService.<ApplyImage>d__1.MoveNext() in D:\a\1\s\Source\DeployerPlatform\Deployer.NetFx\DismImageService.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.WindowsDeployer.<Deploy>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Tasks.DeployWindows.<Execute>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Execution.ScriptRunner.<Run>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Execution.ScriptRunner.<Run>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Raspberry.WoaDeployer.<Deploy>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Deployer.Raspberry.Gui.ViewModels.DeploymentViewModel.<Deploy>d__20.MoveNext() in D:\a\1\s\Source\Deployer.Raspberry.Gui\ViewModels\DeploymentViewModel.cs:line 82
2019-02-20 13:12:26.214 -05:00 [Information] Error: There has been a problem during deployment: DISM exited with code 5.
2019-02-20 13:13:49.741 -05:00 [Information] Downloading UEFI
2019-02-20 13:13:49.741 -05:00 [Warning] UEFI was already downloaded. Skipping download.
2019-02-20 13:13:49.753 -05:00 [Information] Zip Unpack from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan95xx-windows/lan9500-wdf-v18.12.18.0.zip to Downloaded\Drivers\LAN95XX
2019-02-20 13:13:49.762 -05:00 [Information] Zip Unpack from http://ww1.microchip.com/downloads/en//softwarelibrary/obj-lan78xx-windows/lan7800-wdf-v18.12.14.0.zip to Downloaded\Drivers\LAN78XX
2019-02-20 13:13:49.769 -05:00 [Information] Zip Unpack from https://pi64.win/wp-content/uploads/2019/02/usb-drivers.zip to Downloaded\Drivers\USB
2019-02-20 13:13:49.775 -05:00 [Information] Fetching from GitHub subfolder: https://github.com/driver1998/bsp/bsp-master/prebuilt to Downloaded\Drivers\BSP Drivers
2019-02-20 13:13:49.775 -05:00 [Warning] "https://github.com/driver1998/bsp""bsp-master/prebuilt" was already downloaded. Skipping download.
2019-02-20 13:13:49.781 -05:00 [Information] License from Downloaded\Drivers\USB\license.md
2019-02-20 13:13:52.377 -05:00 [Information] Deploying Windows
2019-02-20 13:13:52.377 -05:00 [Information] Flashing GPT image...
2019-02-20 13:13:52.377 -05:00 [Verbose] We are about to run Etcher: "Core\Tools\Etcher-Cli\x86\Etcher" "-d \\.\PHYSICALDRIVE1 \"Core\gpt.zip\" --yes --no-unmount"
2019-02-20 13:13:52.378 -05:00 [Verbose] Starting process { FileName: "Core\Tools\Etcher-Cli\x86\Etcher", Arguments: "-d \\.\PHYSICALDRIVE1 \"Core\gpt.zip\" --yes --no-unmount" }
2019-02-20 13:13:52.458 -05:00 [Verbose] Process started sucessfully
2019-02-20 13:15:14.407 -05:00 [Information] Validating flashed image...
2019-02-20 13:16:14.967 -05:00 [Information] GPT image flashed
2019-02-20 13:16:14.968 -05:00 [Verbose] Creating Windows partition...
2019-02-20 13:16:15.642 -05:00 [Verbose] Mounting volume "Label: , Size: 0 b, Partition: Disk: Number: 1, Size: 29.72 GB, AllocatedSize: 29.72 GB, Number: 3, Letter: "
2019-02-20 13:16:26.331 -05:00 [Verbose] Windows Partition created successfully
2019-02-20 13:16:26.331 -05:00 [Information] Preparing for Windows deployment
2019-02-20 13:16:26.331 -05:00 [Verbose] Getting "WindowsARM" volume
2019-02-20 13:16:27.365 -05:00 [Information] Deploying Windows...
2019-02-20 13:16:27.365 -05:00 [Verbose] Checking image at "F:\sources\install.wim", with index "F:\sources\install.wim"
2019-02-20 13:16:27.365 -05:00 [Verbose] Image file at '"F:\sources\install.wim"' exists
2019-02-20 13:16:27.365 -05:00 [Verbose] Getting WIM stream
2019-02-20 13:16:27.365 -05:00 [Verbose] (WIM) Finding Magic Bytes...
2019-02-20 13:16:27.365 -05:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-02-20 13:16:27.365 -05:00 [Verbose] (WIM) Finding WIM XML Data...
2019-02-20 13:16:27.365 -05:00 [Verbose] (WIM) Found WIM XML Data at 043418977782
2019-02-20 13:16:27.375 -05:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "4341897778", Images: [ImageMetadata { DirectoryCount: "22565", FileCount: "98622", TotalBytes: "17049204181", HardLinkBytes: "6590715483", CreationTime: Time { HighPart: "0x01D44CED", LowPart: "0x43022989" }, LastModificationTime: Time { HighPart: "0x01D4C944", LowPart: "0x0061F20D" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "Microsoft® Windows® Operating System", EditionId: "Professional", InstallationType: "Client", ServicingData: ServicingData { GdrDuRevision: "0", PKeyConfigVersion: "10.0.17763.1;2016-01-01T00:00:00Z" }, ProductType: "WinNT", ProductSuite: "Terminal Server", Languages: Languages { Language: "en-US", Default: "en-US" }, Version: Version { Major: "10", Minor: "0", Build: "17763", SpBuild: "292", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Pro", Description: "Windows 10 Pro", Flags: null, DiplayName: "Windows 10 Pro", DisplayDescription: "Windows 10 Pro", Index: "1" }] }
2019-02-20 13:16:27.375 -05:00 [Verbose] We are about to run DISM: "C:\WINDOWS\SysNative\dism.exe" "/Apply-Image  /ImageFile:\"F:\sources\install.wim\" /Index:1 /ApplyDir:H:\"
2019-02-20 13:16:27.375 -05:00 [Verbose] Starting process { FileName: "C:\WINDOWS\SysNative\dism.exe", Arguments: "/Apply-Image  /ImageFile:\"F:\sources\install.wim\" /Index:1 /ApplyDir:H:\" }
2019-02-20 13:16:27.401 -05:00 [Verbose] Process started sucessfully
2019-02-20 14:04:59.539 -05:00 [Verbose] Making Windows installation bootable...
2019-02-20 14:04:59.542 -05:00 [Verbose] Getting "EFIESP" volume
2019-02-20 14:05:02.831 -05:00 [Verbose] Getting "WindowsARM" volume
2019-02-20 14:05:03.422 -05:00 [Verbose] Making Windows installation bootable...
2019-02-20 14:05:03.430 -05:00 [Verbose] Starting process { FileName: "C:\WINDOWS\SysNative\bcdboot.exe", Arguments: "H:\Windows /f UEFI /s E:" }
2019-02-20 14:05:03.528 -05:00 [Verbose] Process started sucessfully
2019-02-20 14:05:14.262 -05:00 [Verbose] Starting process { FileName: "C:\WINDOWS\SysNative\bcdedit.exe", Arguments: "/STORE \"E:\EFI\Microsoft\Boot\BCD\" /set {default} testsigning on" }
2019-02-20 14:05:14.353 -05:00 [Verbose] Process started successfully
2019-02-20 14:05:14.614 -05:00 [Verbose] Process output "The operation completed successfully.
"
2019-02-20 14:05:14.615 -05:00 [Verbose] Starting process { FileName: "C:\WINDOWS\SysNative\bcdedit.exe", Arguments: "/STORE \"E:\EFI\Microsoft\Boot\BCD\" /set {default} recoveryenabled no" }
2019-02-20 14:05:14.676 -05:00 [Verbose] Process started successfully
2019-02-20 14:05:14.923 -05:00 [Verbose] Process output "The operation completed successfully.
"
2019-02-20 14:05:14.924 -05:00 [Verbose] Starting process { FileName: "C:\WINDOWS\SysNative\bcdedit.exe", Arguments: "/STORE \"E:\EFI\Microsoft\Boot\BCD\" /set {default} nointegritychecks on" }
2019-02-20 14:05:14.945 -05:00 [Verbose] Process started successfully
2019-02-20 14:05:16.250 -05:00 [Verbose] Process output "The operation completed successfully.
"
2019-02-20 14:05:16.252 -05:00 [Verbose] Setting partition type to "Disk: Number: 1, Size: 29.72 GB, AllocatedSize: 29.72 GB, Number: 1" from "Guid: ebd0a0a2-b9e5-4433-87c0-68b6b72699c7" to "Guid: c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
2019-02-20 14:05:16.512 -05:00 [Verbose] Partition type set
2019-02-20 14:05:16.512 -05:00 [Verbose] Getting "EFIESP" volume
2019-02-20 14:05:17.155 -05:00 [Verbose] We shouldn't be able to get a reference to the Boot volume.
2019-02-20 14:05:17.157 -05:00 [Verbose] Updated Boot Volume: { Label: "EFIESP", Partition: Partition { Disk: Disk { LowLevelApi: LowLevelApi {  }, Number: 1, Size: ByteSize { Bits: 255319867392, Bytes: 31914983424, KiloBytes: 31166976, MegaBytes: 30436.5, GigaBytes: 29.72314453125, TeraBytes: 0.0290265083312988, PetaBytes: 2.8346199542284E-05, LargestWholeNumberSymbol: "GB", LargestWholeNumberValue: 29.72314453125 }, AllocatedSize: ByteSize { Bits: 255294701568, Bytes: 31911837696, KiloBytes: 31163904, MegaBytes: 30433.5, GigaBytes: 29.72021484375, TeraBytes: 0.0290236473083496, PetaBytes: 2.83434055745602E-05, LargestWholeNumberSymbol: "GB", LargestWholeNumberValue: 29.72021484375 }, AvailableSize: ByteSize { Bits: 25165824, Bytes: 3145728, KiloBytes: 3072, MegaBytes: 3, GigaBytes: 0.0029296875, TeraBytes: 2.86102294921875E-06, PetaBytes: 2.79396772384644E-09, LargestWholeNumberSymbol: "MB", LargestWholeNumberValue: 3 }, IsSystem: False, IsBoot: False, IsReadOnly: False, IsOffline: False, FriendlyName: "VID:03 SL32G" }, Number: 1, Id: "{00000000-0000-0000-0000-010000000000}SD\DISK&GENERIC&SL32G&8.0\6&12F07D6C&0&6007130E&0:DESKTOP-068HCAF", Letter: E, PartitionType: PartitionType { Name: "EFI System Partition", Guid: c12a7328-f81f-11d2-ba4b-00a0c93ec93b }, LowLevelApi: LowLevelApi {  } } }
2019-02-20 14:05:17.203 -05:00 [Information] Copying directory to BOOT: Downloaded\UEFI\RELEASE to 
2019-02-20 14:05:17.418 -05:00 [Verbose] Setting partition type to "Disk: Number: 1, Size: 29.72 GB, AllocatedSize: 29.72 GB, Number: 1" from "Guid: c12a7328-f81f-11d2-ba4b-00a0c93ec93b" to "Guid: ebd0a0a2-b9e5-4433-87c0-68b6b72699c7"
2019-02-20 14:05:17.565 -05:00 [Verbose] Partition type set
2019-02-20 14:05:17.565 -05:00 [Verbose] Getting "EFIESP" volume
2019-02-20 14:05:18.183 -05:00 [Verbose] Copying directory "Downloaded\UEFI\RELEASE" to "E:\"
2019-02-20 14:05:26.788 -05:00 [Verbose] Setting partition type to "Disk: Number: 1, Size: 29.72 GB, AllocatedSize: 29.72 GB, Number: 1" from "Guid: ebd0a0a2-b9e5-4433-87c0-68b6b72699c7" to "Guid: c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
2019-02-20 14:05:27.036 -05:00 [Verbose] Partition type set
2019-02-20 14:05:27.047 -05:00 [Information] Injecting drivers
2019-02-20 14:05:27.049 -05:00 [Verbose] Getting "WindowsARM" volume
2019-02-20 14:05:27.770 -05:00 [Verbose] Starting process { FileName: "C:\WINDOWS\SysNative\dism.exe", Arguments: "/Add-Driver /Image:H:\ /Driver:\"Downloaded\Drivers\BSP Drivers\" /Recurse /ForceUnsigned" }
2019-02-20 14:05:27.852 -05:00 [Verbose] Process started sucessfully
2019-02-20 14:05:28.185 -05:00 [Verbose] 
2019-02-20 14:05:28.185 -05:00 [Verbose] Deployment Image Servicing and Management tool
2019-02-20 14:05:28.185 -05:00 [Verbose] Version: 10.0.17763.1
2019-02-20 14:05:28.185 -05:00 [Verbose] 
2019-02-20 14:05:41.518 -05:00 [Verbose] Image Version: 10.0.17763.292
2019-02-20 14:05:41.518 -05:00 [Verbose] 
2019-02-20 14:05:46.833 -05:00 [Verbose] Searching for driver packages to install...
2019-02-20 14:05:48.540 -05:00 [Verbose] Found 12 driver package(s) to install.
2019-02-20 14:05:49.039 -05:00 [Verbose] Installing 1 of 12 - C:\Downloads\WOADeployer\Downloaded\Drivers\BSP Drivers\bcm2836pwm\bcm2836pwm.inf: The driver package was successfully installed.
2019-02-20 14:05:49.405 -05:00 [Verbose] Installing 2 of 12 - C:\Downloads\WOADeployer\Downloaded\Drivers\BSP Drivers\bcm2836sdhc\bcm2836sdhc.inf: The driver package was successfully installed.
2019-02-20 14:05:49.813 -05:00 [Verbose] Installing 3 of 12 - C:\Downloads\WOADeployer\Downloaded\Drivers\BSP Drivers\bcmauxspi\bcmauxspi.inf: The driver package was successfully installed.
2019-02-20 14:05:50.170 -05:00 [Verbose] Installing 4 of 12 - C:\Downloads\WOADeployer\Downloaded\Drivers\BSP Drivers\bcmgpio\bcmgpio.inf: The driver package was successfully installed.
2019-02-20 14:05:50.603 -05:00 [Verbose] Installing 5 of 12 - C:\Downloads\WOADeployer\Downloaded\Drivers\BSP Drivers\bcmi2c\bcmi2c.inf: The driver package was successfully installed.
2019-02-20 14:05:51.095 -05:00 [Verbose] Installing 6 of 12 - C:\Downloads\WOADeployer\Downloaded\Drivers\BSP Drivers\bcmspi\bcmspi.inf: The driver package was successfully installed.
2019-02-20 14:05:51.513 -05:00 [Verbose] Installing 7 of 12 - C:\Downloads\WOADeployer\Downloaded\Drivers\BSP Drivers\pi_miniuart\pi_miniuart.inf: The driver package was successfully installed.
2019-02-20 14:05:51.889 -05:00 [Verbose] Installing 8 of 12 - C:\Downloads\WOADeployer\Downloaded\Drivers\BSP Drivers\rpiq\RPIQ.inf: The driver package was successfully installed.
2019-02-20 14:05:52.372 -05:00 [Verbose] Installing 9 of 12 - C:\Downloads\WOADeployer\Downloaded\Drivers\BSP Drivers\rpisdhc\rpisdhc.inf: The driver package was successfully installed.
2019-02-20 14:05:53.476 -05:00 [Verbose] Installing 10 of 12 - C:\Downloads\WOADeployer\Downloaded\Drivers\BSP Drivers\rpiwav\rpiwav.inf: The driver package was successfully installed.
2019-02-20 14:05:54.111 -05:00 [Verbose] Installing 11 of 12 - C:\Downloads\WOADeployer\Downloaded\Drivers\BSP Drivers\SerPL011\SerPL011.inf: The driver package was successfully installed.
2019-02-20 14:05:54.693 -05:00 [Verbose] Installing 12 of 12 - C:\Downloads\WOADeployer\Downloaded\Drivers\BSP Drivers\vchiq\vchiq.inf: The driver package was successfully installed.
2019-02-20 14:05:54.693 -05:00 [Verbose] The operation completed successfully.
2019-02-20 14:05:59.779 -05:00 [Information] Injecting drivers
2019-02-20 14:05:59.779 -05:00 [Verbose] Getting "WindowsARM" volume
2019-02-20 14:06:00.371 -05:00 [Verbose] Starting process { FileName: "C:\WINDOWS\SysNative\dism.exe", Arguments: "/Add-Driver /Image:H:\ /Driver:\"Downloaded\Drivers\LAN95XX\ndis650\arm64\" /Recurse /ForceUnsigned" }
2019-02-20 14:06:00.423 -05:00 [Verbose] Process started sucessfully
2019-02-20 14:06:00.662 -05:00 [Verbose] 
2019-02-20 14:06:00.662 -05:00 [Verbose] Deployment Image Servicing and Management tool
2019-02-20 14:06:00.662 -05:00 [Verbose] Version: 10.0.17763.1
2019-02-20 14:06:00.662 -05:00 [Verbose] 
2019-02-20 14:06:02.449 -05:00 [Verbose] Image Version: 10.0.17763.292
2019-02-20 14:06:02.449 -05:00 [Verbose] 
2019-02-20 14:06:06.346 -05:00 [Verbose] Searching for driver packages to install...
2019-02-20 14:06:06.723 -05:00 [Verbose] Found 1 driver package(s) to install.
2019-02-20 14:06:07.250 -05:00 [Verbose] Installing 1 of 1 - C:\Downloads\WOADeployer\Downloaded\Drivers\LAN95XX\ndis650\arm64\net9500-arm64-n650f.inf: The driver package was successfully installed.
2019-02-20 14:06:07.251 -05:00 [Verbose] The operation completed successfully.
2019-02-20 14:06:08.364 -05:00 [Information] Injecting drivers
2019-02-20 14:06:08.364 -05:00 [Verbose] Getting "WindowsARM" volume
2019-02-20 14:06:08.940 -05:00 [Verbose] Starting process { FileName: "C:\WINDOWS\SysNative\dism.exe", Arguments: "/Add-Driver /Image:H:\ /Driver:\"Downloaded\Drivers\LAN78XX\ndis650\arm64\" /Recurse /ForceUnsigned" }
2019-02-20 14:06:08.966 -05:00 [Verbose] Process started sucessfully
2019-02-20 14:06:09.131 -05:00 [Verbose] 
2019-02-20 14:06:09.131 -05:00 [Verbose] Deployment Image Servicing and Management tool
2019-02-20 14:06:09.131 -05:00 [Verbose] Version: 10.0.17763.1
2019-02-20 14:06:09.131 -05:00 [Verbose] 
2019-02-20 14:06:10.641 -05:00 [Verbose] Image Version: 10.0.17763.292
2019-02-20 14:06:10.641 -05:00 [Verbose] 
2019-02-20 14:06:14.096 -05:00 [Verbose] Searching for driver packages to install...
2019-02-20 14:06:14.456 -05:00 [Verbose] Found 1 driver package(s) to install.
2019-02-20 14:06:15.195 -05:00 [Verbose] Installing 1 of 1 - C:\Downloads\WOADeployer\Downloaded\Drivers\LAN78XX\ndis650\arm64\net7800-arm64-n650f.inf: The driver package was successfully installed.
2019-02-20 14:06:15.195 -05:00 [Verbose] The operation completed successfully.
2019-02-20 14:06:16.630 -05:00 [Information] Injecting drivers
2019-02-20 14:06:16.630 -05:00 [Verbose] Getting "WindowsARM" volume
2019-02-20 14:06:17.209 -05:00 [Verbose] Starting process { FileName: "C:\WINDOWS\SysNative\dism.exe", Arguments: "/Add-Driver /Image:H:\ /Driver:\"Downloaded\Drivers\USB\" /Recurse /ForceUnsigned" }
2019-02-20 14:06:17.254 -05:00 [Verbose] Process started sucessfully
2019-02-20 14:06:17.472 -05:00 [Verbose] 
2019-02-20 14:06:17.473 -05:00 [Verbose] Deployment Image Servicing and Management tool
2019-02-20 14:06:17.473 -05:00 [Verbose] Version: 10.0.17763.1
2019-02-20 14:06:17.473 -05:00 [Verbose] 
2019-02-20 14:06:19.142 -05:00 [Verbose] Image Version: 10.0.17763.292
2019-02-20 14:06:19.142 -05:00 [Verbose] 
2019-02-20 14:06:22.440 -05:00 [Verbose] Searching for driver packages to install...
2019-02-20 14:06:22.877 -05:00 [Verbose] Found 2 driver package(s) to install.
2019-02-20 14:06:23.781 -05:00 [Verbose] Installing 1 of 2 - C:\Downloads\WOADeployer\Downloaded\Drivers\USB\mcci_dwchsotg_hcd.inf: The driver package was successfully installed.
2019-02-20 14:06:24.526 -05:00 [Verbose] Installing 2 of 2 - C:\Downloads\WOADeployer\Downloaded\Drivers\USB\mcci_dwchsotg_hub.inf: The driver package was successfully installed.
2019-02-20 14:06:24.526 -05:00 [Verbose] The operation completed successfully.

**Comment by SuperJMN** [comment]
It seems you got a DISM error 5. This means in 99% of cases that the problem is the .wim file or DISM itself. WOA Deployer only invokes DISM to perform its tasks. 

Please, re-open this if it keeps happening after you have retried and double checked that the .wim file isn't corrupted.
